name: Simple Test

on:
  push:
    branches:
      - main
      - cicd        # runs on these branches
  pull_request:
    branches:
      - main
      - cicd

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v5

      # Step 2: Setup Python
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # Step 3: Install dependencies
      - name: Install dependencies
        run: pip install -r requirements.txt

      # Step 4: Run tests with pytest
      - name: Run tests
        run: pytest
      - run: pytest

